# Generated by Django 5.2.9 on 2026-04-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_votes_timestamp_alter_position_max_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='face_photo',
            field=models.ImageField(blank=True, null=True, upload_to='faces/'),
        ),
    ]
